configure: warn when gcc_syslibs_devel is not installed
Change-Id: I03177c7afcde64088cfed5e68c3823f69bd8a8bc
Reviewed-on: https://review.haiku-os.org/c/haiku/+/10713
Reviewed-by: waddlesplash <waddlesplash@gmail.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -328,6 +328,13 @@ standard_gcc_settings()
 			bootLibgcc=`$gcc -print-file-name=libgcc.a`
 			bootLibSupCxx=`$gcc -print-file-name=libsupc++.a`
 
+			if [ "$bootLibSupCxx" = "libsupc++.a" ]; then
+				echo "libsupc++.a could not be found!"
+				if [ "$HOST_PLATFORM" = "haiku_host" ]; then
+					echo "try installing gcc_syslibs_devel or using the cross-tools"
+				fi
+				exit 1
+			fi
 			local headersBase=$gccdir/../../../..
 			local headers=$headersBase/$gccMachine/include/c++/$gccRawVersion
 			if [ ! -d $headers ]; then
