build: Fixes for arm64 macOS
* macOS ships an ancient version of GNU Bison which wants
  an '=' after %name-prefix

* macOS awk doesn't support strftime, so try to find a working
  awk.

* _haiku_build_{open,openat,fcntl} are declared and defined with
  different prototypes (variadic vs non-variadic). This is bad
  on its own, but it "happens to" work on most platforms since
  variadic parameters are usually passed in registers, same as other
  arguments. On arm64 macOS, variadic parameters are always passed
  on the stack, so you get weird and confusing bugs when using
  these functions.

Change-Id: I8cee9ecac0ac9b039be6b7e35ceaf8ad7c0f4c44
Reviewed-on: https://review.haiku-os.org/c/haiku/+/10468
Tested-by: Commit checker robot <no-reply+buildbot@haiku-os.org>
Reviewed-by: waddlesplash <waddlesplash@gmail.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -931,6 +931,22 @@ if [ "$("$HAIKU_NASM" -hf | grep -c elf'[36][24] ')" -ne "2" ]; then
 	exit 1
 fi
 
+# locate awk
+if [ -z "$HOST_AWK" ]; then
+	HOST_AWK="awk"
+	awk 'BEGIN{strftime()}' 2>/dev/null
+	if [ $? -ne 0 ]; then
+		# awk does not support strftime, try gawk
+		HOST_AWK="gawk"
+	fi
+fi
+$HOST_AWK 'BEGIN{strftime()}' 2>/dev/null
+if [ $? -ne 0 ]; then
+	echo "A working awk was not found. Install gawk or specify"
+	echo "a different awk with HOST_AWK."
+	exit 1
+fi
+
 # create output directory
 mkdir -p "$buildOutputDir" || exit 1
 
@@ -1171,6 +1187,7 @@ HOST_OBJCOPY				?= ${HOST_GCC_OBJCOPY} ;
 HOST_EXTENDED_REGEX_SED		?= ${HOST_EXTENDED_REGEX_SED} ;
 HOST_SHA256					?= ${HOST_SHA256} ;
 HOST_PYTHON					?= ${HOST_PYTHON} ;
+HOST_AWK					?= ${HOST_AWK} ;
 HOST_WGET_RETRY_ON_HOST_ERROR			?= ${HOST_WGET_RETRY_ON_HOST_ERROR} ;
 HAIKU_NASM					?= ${HAIKU_NASM} ;
 
