Add variable noDownloads to build_haiku_image.
* If noDownloads is set, show an error when a download is requested.

diff --git a/build/scripts/build_haiku_image b/build/scripts/build_haiku_image
--- a/build/scripts/build_haiku_image
+++ b/build/scripts/build_haiku_image
@@ -16,6 +16,7 @@ set -o errexit
 # imageSize
 # imageLabel
 # resolvePackageDependencies
+# noDownloads
 # updateAllPackages
 # updateOnly
 # dontClearImage
@@ -214,6 +215,11 @@ downloadFile()
 	path=$2
 
 	if [ ! -f "$path" ]; then
+		if [ "$noDownloads" == "1" ]; then
+			echo "ERROR: Would need to download $url, but HAIKU_NO_DOWNLOADS "
+				"is set!"
+			exit 1
+		fi
 		wget -O "$path" "$url"
 	fi
 }
