Add new configuration option --no-downloads.
* If --no-downloads has been given, Haiku will be built without
  trying to download anything, all required packages need to be put
  into the download folder manually (the build will stop on missing
  packages).
* As the required HaikuPorts repository can't be downloaded in this
  mode, a local repository is created during the build, which only
  contains the packages available in the downloads folder.

This is useful for building Haiku completely from source.

diff --git a/build/jam/FileRules b/build/jam/FileRules
--- a/build/jam/FileRules
+++ b/build/jam/FileRules
@@ -468,6 +468,10 @@ rule DownloadLocatedFile target : url : source
 actions DownloadLocatedFile1
 {
 	source="$(2)"
+	if [ "$(HAIKU_NO_DOWNLOADS)" = 1 ]; then
+		echo "ERROR: Would need to download $(URL), but HAIKU_NO_DOWNLOADS is set!" ;
+		exit 1
+	fi
 	wget -O "$(1)" $(URL) || exit 1
 	touch "$(1)"
 }
